Warehouse time
ActionIQ/spark-snowflake pull request #22
Opened 2024-04-23 20:24 UTC by ShaoFuWu

2024-04-26 21:25 UTC, yannistze commented on src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala
> +                 |""".stripMargin
https://github.com/ActionIQ/flame/pull/585#discussion_r1581546830

2024-04-26 21:27 UTC, yannistze commented on src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
> +      sc.setLocalProperty("querySubmissionTime", startTime.toString)
Hmm, why are you passing it like this here ? Can you help me understand ?

2024-04-26 21:28 UTC, yannistze commented on src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala
> +      Some(context.getLocalProperty("querySubmissionTime")),
https://github.com/ActionIQ/flame/pull/585#discussion_r1581538264

2024-05-13 14:03 UTC, ShaoFuWu commented
https://app.datadoghq.com/logs?query=%40trace_id%3A8796541c931cd376%20snowflake%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2C%40trace_id&event=AgAAAY9jwqzQOBEzuAAAAAAAAAAYAAAAAEFZOWp3c0EtQUFEaE15cThYQ0trMndBQwAAACQAAAAAMDE4ZjYzYzItZjFjMi00YWFhLWI1NmEtYTJmMGQwYzc0ODY0&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1715279163627&to_ts=1715365563627&live=true
![Screenshot 2024-05-10 at 2 29 46 PM](https://github.com/ActionIQ/spark-snowflake/assets/87321568/366eef23-6649-4f9a-8b54-f14d1d9b4a09)

2024-05-15 15:18 UTC, yannistze commented on src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala
> +  var firstRowReadAt = java.time.Instant.now()
Same question as the other PR, why do you need this in 2 places 🤔 ?

2024-05-19 23:29 UTC, MasterDDT requested changes
Need to merge the other Flame PR and use the new method right? Also use the same pattern for `firstRowReadAt`

2024-05-22 19:38 UTC, yannistze commented on build.sbt
> -import scala.util.Properties
Did you track when this was added before you removed to be certain ?

2024-05-22 19:38 UTC, yannistze commented on src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala
> +  var firstRowReadAt = java.time.Instant.now()
You need to fix this as in the other PR

2024-05-22 19:38 UTC, yannistze commented on src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala
> +  var firstRowReadAt = java.time.Instant.now()
`var firstRowReadAt: Option[Instant] = None`

2024-05-23 03:05 UTC, ShaoFuWu commented on build.sbt
> -import scala.util.Properties
yeah I think the usage of `Properties` was removed here https://github.com/ActionIQ/spark-snowflake/pull/5/files should be safe to remove 👍

2024-05-23 14:42 UTC, yannistze approved these changes
LGTM 👍

2024-05-23 14:50 UTC, merged